; =====================================================================
; UNIVERSIDAD DE PAMPLONA - INGENIERÍA MECATRÓNICA
; Proyecto: Estación Meteorológica IoT con ESP32
; Archivo: platformio.ini (Configuración del Entorno de Desarrollo)
; Descripción: Define la plataforma, librerías, velocidad de carga y 
;              mapeo físico de la pantalla TFT paralela de 8 bits (ILI9341).
; Fecha: Junio 2026
; =====================================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Parámetros de comunicación serial y flasheo
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/ttyUSB0  ; Puerto de comunicación en Linux/macOS (Cambiar a COM X si usas Windows)

; 📚 Gestor de Dependencias (Librerías oficiales del proyecto)
lib_deps =
  bodmer/TFT_eSPI @ ^2.5.43
  adafruit/RTClib @ ^2.1.4
  adafruit/Adafruit BME280 Library @ ^2.2.4
  adafruit/Adafruit BusIO @ ^1.16.1
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  claws/BH1750 @ ^1.3.0
   
; Flags de Compilación (Parámetros de preprocesador para el hardware)
build_flags =
  ; --- Configuración Base del Driver Gráfico ---
  -D USER_SETUP_LOADED=1    ; Indica a TFT_eSPI que ignore su archivo interno y use estos flags
  -D ESP32_PARALLEL=1       ; Activa el bus paralelo de 8 bits (Obligatorio para esta configuración de pantalla)
  -D ILI9341_DRIVER=1       ; Define el chip controlador integrado en tu pantalla TFT
  
  ; --- Dimensiones Físicas del Panel ---
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320

  ; --- Fuentes Tipográficas Cargadas en la Memoria Flash ---
  -D LOAD_GLCD=1            ; Fuente estándar 1 (Ideal para textos fijos muy pequeños)
  -D LOAD_FONT2=1           ; Fuente pequeña y clara 2 (Usada en etiquetas de sensores)
  -D LOAD_FONT4=1           ; Fuente mediana 4 (Perfecta para títulos y encabezados)
  -D LOAD_FONT6=1           ; Fuente grande 6 (Diseñada exclusivamente para números del reloj)
  
  ; --- 📌 Pines de Control de la Pantalla TFT ---
  -D TFT_RD=4               ; Read: Línea de lectura (GPIO 4)
  -D TFT_WR=33              ; Write: Línea de escritura (GPIO 33)
  -D TFT_DC=32              ; Data/Command: Selección de registro de datos o comandos (GPIO 32)
  -D TFT_CS=2               ; Chip Select: Habilitador del bus de la pantalla (GPIO 2)
  -D TFT_RST=15             ; Reset: Pin de reinicio de hardware para la TFT (GPIO 15)

  ; --- 🚌 Bus de Datos de 8 Bits (Mapeo de los Pines D0 a D7) ---
  -D TFT_D0=12              ; Bit de datos 0 (GPIO 12)
  -D TFT_D1=13              ; Bit de datos 1 (GPIO 13)
  -D TFT_D2=26              ; Bit de datos 2 (GPIO 26)
  -D TFT_D3=25              ; Bit de datos 3 (GPIO 25)
  -D TFT_D4=17              ; Bit de datos 4 (GPIO 17)
  -D TFT_D5=16              ; Bit de datos 5 (GPIO 16)
  -D TFT_D6=27              ; Bit de datos 6 (GPIO 27)
  -D TFT_D7=14              ; Bit de datos 7 (GPIO 14)